### ISSUE TITLE
Declarative setuptools build

### ISSUE THREAD

**Issue by tucked** [dmtucker/backlog#49]
https://github.com/pypa/setuptools/pull/1675

**Comment by dmtucker** [comment]
> **Important:** A `setup.py` file containing a `setup()` function call is still required even if your configuration resides in `setup.cfg`.

https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files

I'll look at #47 first (which I think generates a `setup.py`).
