### ISSUE TITLE
appdirs

### ISSUE THREAD

**Issue by dmtucker** [dmtucker/backlog#60]
https://github.com/dmtucker/backlog/blob/e8463ffd947aa3c8dc9c8bece0a70ce621eeb068/src/backlog/cli.py#L15

https://pypi.org/project/appdirs/

**Comment by reillysiemens** [comment]
Since you're already using Click, @dmtucker, I'd recommend having a look at [`click.get_app_dir()`](https://click.palletsprojects.com/en/7.x/utils/#finding-application-folders). In case you haven't already... 😅

**Comment by dmtucker** [comment]
Nice! Thank you... I was not aware of that!
