### ISSUE TITLE
Use `twine check` instead of `setup.py check`

### ISSUE THREAD

**Issue by tucked** [dmtucker/backlog#64]
https://github.com/dmtucker/backlog/blob/80a5abfc3d97d4224637b495302fee7e01613c6e/test_setup.py#L11-L20
> warning: Check: This command has been deprecated. Use `twine check` instead: https://packaging.python.org/guides/making-a-pypi-friendly-readme#validating-restructuredtext-markup

**Comment by dmtucker** [comment]
https://github.com/pypa/readme_renderer/blob/2c42c8ef564a421ab4f3193797d2c7214c6ca6a1/readme_renderer/integration/distutils.py#L69
